issues:
  exclude-dirs:
  - it

run:
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
  # Default
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused

  # Additionally linters
  - bodyclose
  - misspell
  - nilerr
  - rowserrcheck
  - sqlclosecheck
  - unparam
  - whitespace